### ISSUE TITLE
Autozoom

### ISSUE THREAD

**Issue by asobina889** [spiritofsim/go-space-crane#4]
Автозум работает на мой субъективный взгляд неадекватно.
Слишком быстро начинает приближать-отдалять в самые неподходящие моменты.

Предложение: вывести управление зумом на кнопки.

**Comment by spiritofsim** [comment]
Выводить зум на кнопки - плохой вариант. управление станет сложнее.
Сейчас зум напрямую зависит от скорости корабля. Чем быстрее, тем дальше зум. Но при этом он не может превышать определенного порога.
Что можно сделать:
1. Сделать зум более плавным
2. Ориентироватся не на скорость, а на близость к ближайшей цели
